### ISSUE TITLE
[expect-type] not.toMatchTypeOf error on non-matching union type

### ISSUE THREAD

**Issue by reiv** [mmkal/ts#219]
Thanks for your work on this library. Ran into this scenario today:

```ts
expectTypeOf<string | number>().toMatchTypeOf<string>(); // Error (as expected)
expectTypeOf<string | number>().not.toMatchTypeOf<string>(); // Error (?)
```

I think the second line should not produce an error.

Edit: same with `expectTypeOf<any>`

`expect-type@0.9.2, typescript@4.1.2`

**Comment by mmkal** [comment]
This is an interesting one, and maybe kind of philosophical. `toMatchTypeOf` corresponds to `extends`. The type logic relies on [distributive conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types), which means that when typescript evaluates `string | number extends string ? true : false`, it produces a union of `string extends string ? true : false` (=> `true`) and `number extends string ? true : false` (=> `false`).

So the result is `true | false`, which is the same as `boolean`. For `toMatchTypeOf` to succeed, it would need to be `true`. For `.not.toMatchTypeOf` to succeed, it would need to be `false`. But it's neither!

I think there's an argument this is correct behaviour, or at least as good as we're likely to get. The type system can't say with confidence that it does or doesn't match, because we haven't really said what "it" is - whether it matches depends on whether it's a string or a number. I can't immediately think of how to "fix" this without side-effects.

In the real world, though, I guess you just want to write a type assertion. So it'd be good to hear about the specific use case. Can you just use `toEqualTypeOf`? This works as expected:

```typescript
expectTypeOf<string | number>().not.toEqualTypeOf<string>()
```

___

Relatedly, I think there's room to improve the UX around union types generally. Maybe something like

```typescript
expectTypeOf<string | number>().excluding<number>().toBeString()
expectTypeOf<string | number>().excluding<boolean>().toBeString() // Error, can't exclude boolean from string | number
```

**Comment by reiv** [comment]
> `toMatchTypeOf` corresponds to `extends`

Right, I assumed `toMatchTypeOf` would be roughly equivalent to "is assignable to this type", i.e.

```ts
const x: string = "foo" as string | number // Error
```

which is why `false` made sense to me. I also assumed that `.not` would simply flip the result of the following assertion, but the actual behavior makes sense with your explanation, and with that in mind I don't necessarily think this needs to be "fixed", just something to be aware of.

> So it'd be good to hear about the specific use case

My use case goes back to the question of assignability. Basically, I'm trying to figure out how best to simulate TypeScript error `ts(2322)` when adding unknown properties to a typed object literal (without actually reproducing the error in the test suite, of course). The type in question is a generic mapped type with well-defined properties (no extras allowed) unioned with a bunch of primitive values (numbers and strings), hence this "discovery".

`toEqualTypeOf` does seem like the better fit here, as it forbids extras, except you have to basically pretend the type being tested _is_ the complete type, optional properties and all, otherwise:

```ts
expectTypeOf<{foo: string}>().toEqualTypeOf<{foo: string, bar?: number}>() // Error, missing bar?
expectTypeOf<{foo: string} | number>().toEqualTypeOf<{foo: string}>() // Error, missing number
```

In the end I settled on this:

```ts
expectTypeOf<Thing | {extra?: any}>().not.toEqualTypeOf<Thing>`()
```

where `Thing` is the complete union type and `extra` is a property I know will not be present in the case I am testing. I think it's close enough, though not sure if 100% sound.

> Relatedly, I think there's room to improve the UX around union types generally

Sounds neat, basically a way of exhaustively testing union members, right?

**Comment by mmkal** [comment]
I'm still not sure I fully understand the scenario, but yeah I don't know if `.not.toEqualTypeOf` is particularly useful there, since it distinguishes between `any` and other types so it might pass too easily. What does the union type `Thing` need to look like?

**Comment by reiv** [comment]
```ts
type ResponsiveProp<T> = T | T[] | { xs?: T, sm?: T, md?: T, ... }
```

This is for a React component, the keys correspond to CSS `@media` breakpoints. Actually a mapped type, because the names of the keys are configurable, but the shape would end up something like this.

I think I could also isolate the object part and test it without the union. Mainly I want to test that no unknown keys can creep into the type because something of something that got refactored down the line. You're right about `any`, in this case I'd substitute in the concrete type of `T`.

Sorry, this is kind of straying off the topic of the original issue.
